# install NGINX, PHP, MySQL.

---

- hosts: all
  become: true
  tasks:

#This section is for DEBIAN/UBUNTU

  - name: update repository for ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install NGINX, PHP, MySQL.
    apt:
      name:
        - nginx
        - php-fpm
        - mariadb-server
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: install PHP and modules
    apt:
      name: 'php-mysql, php-curl, php-mbstring, php-imagick, php-xml, php-zip'
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]


#This section is for CENTOS/RHEL

  - name: update repository for CentOS
    dnf:
      update_cache: yes
    when: ansible_distribution in ["RHEL", "CentOS", "CentOS/RHEL", "Fedora"]

  - name: install NGINX, PHP, MySQL.
    dnf:
      name:
        - nginx
        - 'php-fpm, php-mysqlnd'
        - mariadb-server
      state: latest
    when: ansible_distribution in ["RHEL", "CentOS", "CentOS/RHEL", "Fedora"]

  - name: install PHP modules
    dnf:
      name: ' php-curl, php-mbstring, php-xml, php-zip'
      state: latest
    when: ansible_distribution in ["RHEL", "CentOS", "CentOS/RHEL", "Fedora"]
